[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 13.0

[font.normal]
family = "DroidSansM Nerd Font"

[font.offset]
y = 2

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[selection]
save_to_clipboard = true
semantic_escape_chars = "@,│`|:\"' ()[]{}<>\t"
