[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_source = '''
source ~/.config/nvim/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_i = 1
on_ft = 'snipppet'
hook_source = '''
source ~/.config/nvim/plugins/neosnippet.rc.vim
'''

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/tabpagebuffer.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_cmd = 'help'

# language

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = 'ruby'

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript'
hook_add = '''
source ~/.config/nvim/plugins/vim-jsx.rc.vim
'''

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'pearofducks/ansible-vim'
on_ft = 'ansible'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
