[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'nanotech/jellybeans.vim'
hook_add = '''
au MyAutoCmd VimEnter * nested colorscheme jellybeans
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_i = 1
hook_add = '''
source ~/.config/nvim/plugins/denite.rc.vim
'''

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'cocopon/vaffle.vim'
hook_add = '''
source ~/.config/nvim/plugins/vaffle.rc.vim
'''
