[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'nanotech/jellybeans.vim'
hook_add = '''
source ~/.config/nvim/plugins/jellybeans.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_i = 1
hook_add = '''
source ~/.config/nvim/plugins/denite.rc.vim
'''

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/tabpagebuffer.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'thinca/vim-qfreplace'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
source ~/.config/nvim/plugins/nerdtree.rc.vim
'''

[[plugins]]
repo = 'scrooloose/nerdcommenter'
hook_add = '''
source ~/.config/nvim/plugins/nerdcommenter.rc.vim
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
source ~/.config/nvim/plugins/vim-easymotion.rc.vim
'''

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
source ~/.config/nvim/plugins/vim-easy-align.rc.vim
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
source ~/.config/nvim/plugins/vim-fugitive.rc.vim
'''

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'bkad/CamelCaseMotion'
hook_add = '''
source ~/.config/nvim/plugins/CamelCaseMotion.rc.vim
'''

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'haya14busa/incsearch.vim'
hook_add = '''
source ~/.config/nvim/plugins/incsearch.rc.vim
'''

[[plugins]]
repo = 'haya14busa/incsearch-fuzzy.vim'

[[plugins]]
repo = 'tpope/vim-surround'
